// <auto-generated />
using AUTO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AUTO.Migrations
{
    [DbContext(typeof(CarSalonDbContext))]
    partial class CarSalonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AUTO.Data.Entities.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 0,
                            Mark = "Mazda",
                            Model = "RX-7",
                            Price = 18000,
                            Speed = 240
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 0,
                            Mark = "Mazda",
                            Model = "RX-8",
                            Price = 20000,
                            Speed = 270
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 0,
                            Mark = "Dodge",
                            Model = "Challenger SRT Demon",
                            Price = 100000,
                            Speed = 380
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 0,
                            Mark = "Nissan",
                            Model = "240sx",
                            Price = 14000,
                            Speed = 210
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 0,
                            Mark = "Nissan",
                            Model = "350z",
                            Price = 19000,
                            Speed = 230
                        });
                });

            modelBuilder.Entity("AUTO.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("AUTO.Data.Entities.Auto", b =>
                {
                    b.HasOne("AUTO.Data.Entities.Company", null)
                        .WithMany("Autos")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AUTO.Data.Entities.Company", b =>
                {
                    b.Navigation("Autos");
                });
#pragma warning restore 612, 618
        }
    }
}
